{"scripts":[
    {"url":"https://raw.githubusercontent.com/nelsonkhan/resources/master/iPlay.js"},
    {"url":"https://raw.githubusercontent.com/nelsonkhan/resources/master/loadRecord.js"}
    {"url":"https://raw.githubusercontent.com/nelsonkhan/resources/master/monthsBetween.js"}
    {"url":"https://raw.githubusercontent.com/nelsonkhan/resources/master/postImages.js"}
    {"url":"https://raw.githubusercontent.com/nelsonkhan/resources/master/randWait.js"}
    {"url":"https://raw.githubusercontent.com/nelsonkhan/resources/master/setVariables.js"}
    {"url":"https://raw.githubusercontent.com/nelsonkhan/resources/master/update.js"}
]}
